/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.11.2.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as controllers_cloth_controller from "../controllers/cloth_controller.js";
import type * as controllers_donation_controller from "../controllers/donation_controller.js";
import type * as controllers_donation_form_controller from "../controllers/donation_form_controller.js";
import type * as controllers_donation_request_controller from "../controllers/donation_request_controller.js";
import type * as controllers_ref_controller_refClothCategory from "../controllers/ref_controller/refClothCategory.js";
import type * as controllers_ref_controller_refDonationRequestStatus from "../controllers/ref_controller/refDonationRequestStatus.js";
import type * as controllers_ref_controller_refDonationStatus from "../controllers/ref_controller/refDonationStatus.js";
import type * as controllers_ref_controller_refNotificationStatus from "../controllers/ref_controller/refNotificationStatus.js";
import type * as controllers_ref_controller_refUserClothStatus from "../controllers/ref_controller/refUserClothStatus.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "controllers/cloth_controller": typeof controllers_cloth_controller;
  "controllers/donation_controller": typeof controllers_donation_controller;
  "controllers/donation_form_controller": typeof controllers_donation_form_controller;
  "controllers/donation_request_controller": typeof controllers_donation_request_controller;
  "controllers/ref_controller/refClothCategory": typeof controllers_ref_controller_refClothCategory;
  "controllers/ref_controller/refDonationRequestStatus": typeof controllers_ref_controller_refDonationRequestStatus;
  "controllers/ref_controller/refDonationStatus": typeof controllers_ref_controller_refDonationStatus;
  "controllers/ref_controller/refNotificationStatus": typeof controllers_ref_controller_refNotificationStatus;
  "controllers/ref_controller/refUserClothStatus": typeof controllers_ref_controller_refUserClothStatus;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
