import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import {ConvexClientProvider} from '@/components/providers/convex-provider';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Sumbang Pakaian',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ConvexClientProvider>
        <body className={inter.className}>{children}</body>
      </ConvexClientProvider>
    </html>
  );
}
