import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import {ConvexClientProvider} from '@/components/providers/convex-provider';
import {Toaster} from 'sonner';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Sumbang Pakaian',
  description: 'Generated by create next app',
  icons: {
    icon: [
      {
        url: '/Logo-icon.svg',
        href: '/Logo-icon.svg',
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider>
          <Toaster position="bottom-right" />
          {children}
        </ConvexClientProvider>
      </body>
    </html>
  );
}
